// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TI_Devops2026_DemoAspCrud.Contexts;

#nullable disable

namespace TI_Devops2026_DemoAspCrud.Migrations
{
    [DbContext(typeof(DemoAspCrudContext))]
    [Migration("20260310103236_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TI_Devops2026_DemoAspCrud.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Instrument à vent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instrument à cordes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Instrument à percussion"
                        });
                });

            modelBuilder.Entity("TI_Devops2026_DemoAspCrud.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_PRODUCT_PRICE", "PRICE >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Super bass fender",
                            Name = "Bass Fender",
                            Price = 140000
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Super saxo de compet",
                            Name = "Saxophone Yanagisawa",
                            Price = 300000
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Super batterie",
                            Name = "Batterie Yamaha",
                            Price = 250000
                        });
                });

            modelBuilder.Entity("TI_Devops2026_DemoAspCrud.Entities.Product", b =>
                {
                    b.HasOne("TI_Devops2026_DemoAspCrud.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TI_Devops2026_DemoAspCrud.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
